name: 'Build a test package'
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v4
      - name: 'Build package'
        id: build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -us -uc
          docker-image: debian:bookworm-slim
      - name: 'Upload artifacts'
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: debian/artifacts
